### ISSUE TITLE
trouble creating "grl" for 5CF logger

### ISSUE THREAD

**Issue by ksakuras** [ksakuras/Siberian-rubythroat-China#10]
Hi Raphael!
    I am processing the data from the 5CF logger (from Russia); I encountered an error at this line (in 4-basic-graph):
grl <- graph_create(static_prob,
                    thr_prob_percentile = gpr$thr_prob_percentile,
                    thr_gs = gpr$thr_gs # threshold km/h
                    )
It wasn't because of labeling, but the error reported as:
"Computing the groundspeed for 297131624 edges for 53 stationary periods in parallel.
[==================================================] 297131624 / 297131624 | sta = 53/53
Trimming the graph:
[==================================================] 104 / 104 
Error: cannot allocate vector of size 256.0 Mb"

Do you know how I should overcome this limit? Is it because of lack of memory or storage space in my computer or something with my data?

I have updated the label file for this 5CF, everything was smooth until here. I am still using the old version of your package, but it shouldn't make too much difference I believe?

**Comment by Rafnuss** [comment]
Hi, Sorry about that. I won't have time to dig into this problem before a while as it's still from the v2. Have you tried with another computer?

**Comment by ksakuras** [comment]
> Hi, Sorry about that. I won't have time to dig into this problem before a while as it's still from the v2. Have you tried with another computer?

Hi!
    No worries! I was just taking the chance in case you have an instant solution haha. I will try to run it on another computer and trouble shooting with some other attempts; otherwise, may I talk to you during my visit to Zurich in the week of Nov 27th- Dec 1st? I also have some ideas that I would like to discuss with you. No rush on this string!

Bests,
Tianhao
