### ISSUE TITLE
stationary 1 calibration and thr_gs setting

### ISSUE THREAD

**Issue by ksakuras** [ksakuras/Siberian-rubythroat-China#4]
Hi Raphael,
    I faced a problem at static map- 3 and basic map -4 codes:
- it started from defining calibration geolocations. I was assuming the bird had moved from our deployment site when the logger started recording data (the pressure is ~2hPa higher than its deployment ground), so I don't have calibrations for gpr$sta == 1. However, I do have the calib_2_sta geolocation (the second year when recapturing), and I wrote in to the .xlsx document. Then when I opened the geopressureviz, the stationary period 1 was still located at my calibrated geolocation "calib_2_sta", even though the pressure data doesnt match. Did your code by default recognize the stationary period 1 as calibratable?
- the second issue arrives when I move on to the 4th part of the code. I cannot generate the "grl" variable, as the error argues that my ground speed set up is not appropriate. But I think it is an mis-alarm, as in the shinyapp website, the first flight from stationary 1 shows as: "Next flight, 1flights - 0hrs, 435km - Inf km/h". I am not sure where it went wrong, but if in this case the speed is "Infinitive", I cannot set any speed threshold to properly generate a "grl" variable to move on. Can you take a look with the example of 5D6 and see how this can be solved? Thank you!
Bests, Tianhao

**Comment by Rafnuss** [comment]
Just following up on this, you still need to fix the first stationary period. the data don't match the imposed first position and it messing up the rest of the trajectory:
![image](https://user-images.githubusercontent.com/7571260/214901246-ecefaa03-f266-454a-9694-2c7114de04e2.png)
