### ISSUE TITLE
error when adding wind to the graph

### ISSUE THREAD

**Issue by ksakuras** [ksakuras/Siberian-rubythroat-China#9]
Hi Raphael,
    This is the small issue I would like to ask you about when we meet:
In the code 5-2-wind-graph_create, line 18 
grl <- graph_add_wind(grl,
  pressure = pam$pressure, filename,
  thr_as = gpr$thr_as
)

The code returns with an error as below, indicating some mismatch in the pressure data:

_Error in graph_add_wind(grl, pressure = pam$pressure, filename, thr_as = gpr$thr_as) : 
  Pressure not matching for 'data/5_wind_graph/5D6/5D6_11.nc'
In addition: There were 22 warnings (use warnings() to see them)_

I have updated my codes and I ran it with the 5D6 data set.

**Comment by Rafnuss** [comment]
Hey, I just updated the code with the fix I suggest. See https://github.com/Rafnuss/GeoPressureR/discussions/62 for more info. Let me know if you have any questions

I managed to get a nice shortest path with geopressureviz:
![image](https://user-images.githubusercontent.com/7571260/214900750-b0c28195-6d4e-43ed-abbe-9b4d57ba0396.png)
